#!/usr/bin/env python3
"""Generate Sources/TokenampKit/Skin/Sprites.generated.swift from skinspec/sprites.json.

skinspec/sprites.json is the single source of truth for every sheet rectangle and every
window-layout coordinate.  Nothing in Swift may hand-type a coordinate that lives there.

The script is idempotent: the same input always produces byte-identical output, and the
file is only rewritten when its contents actually change.

    python3 scripts/gen_sprites_swift.py [--check]

--check exits non-zero when the checked-in generated file is stale.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPEC = os.path.join(ROOT, "skinspec", "sprites.json")
OUT = os.path.join(ROOT, "Sources", "TokenampKit", "Skin", "Sprites.generated.swift")

# Order matters only for readability of the generated file.
SHEET_CASE = {
    "main": "main",
    "titlebar": "titlebar",
    "cbuttons": "cbuttons",
    "shufrep": "shufrep",
    "posbar": "posbar",
    "volume": "volume",
    "balance": "balance",
    "monoster": "monoster",
    "playpaus": "playpaus",
    "numbers": "numbers",
    "nums_ex": "numsEx",
    "text": "text",
    "eqmain": "eqmain",
    "pledit": "pledit",
}

WINDOW_ENUM = {"main": "Main", "shade": "Shade", "eq": "EQ", "playlist": "Playlist"}

# Swift keywords that can appear as a JSON layout key and must be back-ticked.
SWIFT_KEYWORDS = {
    "repeat", "default", "case", "class", "enum", "struct", "in", "for", "while", "let", "var",
    "func", "return", "if", "else", "switch", "break", "continue", "where", "as", "is", "try",
    "throw", "guard", "defer", "operator", "protocol", "extension", "import", "init", "deinit",
    "subscript", "static", "public", "private", "internal", "open", "true", "false", "nil", "self",
}


def ident(name: str) -> str:
    return "`%s`" % name if name in SWIFT_KEYWORDS else name


def swift_string(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    return '"%s"' % out


def is_int_list(v, n=None):
    return (
        isinstance(v, list)
        and (n is None or len(v) == n)
        and all(isinstance(e, int) and not isinstance(e, bool) for e in v)
    )


def num_literal(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    return repr(float(v))


def emit_value(raw_key, value, indent, lines):
    """Emit one `public static let <key> = ...` for a layout entry."""
    pad = " " * indent
    key = ident(raw_key)
    if is_int_list(value, 4):
        lines.append("%spublic static let %s = SpriteRect(%d, %d, %d, %d)" % ((pad, key) + tuple(value)))
    elif is_int_list(value, 2):
        lines.append("%spublic static let %s = SkinPair(%d, %d)" % (pad, key, value[0], value[1]))
    elif isinstance(value, list) and value and all(is_int_list(e, 4) for e in value):
        body = ", ".join("SpriteRect(%d, %d, %d, %d)" % tuple(e) for e in value)
        lines.append("%spublic static let %s: [SpriteRect] = [%s]" % (pad, key, body))
    elif isinstance(value, list) and value and all(is_int_list(e, 2) for e in value):
        body = ", ".join("SkinPair(%d, %d)" % (e[0], e[1]) for e in value)
        lines.append("%spublic static let %s: [SkinPair] = [%s]" % (pad, key, body))
    elif isinstance(value, dict) and value and all(is_int_list(v, 4) for v in value.values()):
        body = ", ".join(
            "(%s, SpriteRect(%d, %d, %d, %d))" % ((swift_string(k),) + tuple(v))
            for k, v in value.items()
        )
        lines.append("%spublic static let %s: [(String, SpriteRect)] = [%s]" % (pad, key, body))
    elif isinstance(value, dict) and value and all(isinstance(v, (int, float)) for v in value.values()):
        name = raw_key[0].upper() + raw_key[1:]
        lines.append("%spublic enum %s {" % (pad, name))
        for k, v in value.items():
            lines.append("%s    public static let %s = %s" % (pad, ident(k), num_literal(v)))
        lines.append("%s}" % pad)
    elif isinstance(value, (int, float)) and not isinstance(value, bool):
        lines.append("%spublic static let %s = %s" % (pad, key, num_literal(value)))
    elif isinstance(value, str):
        lines.append("%spublic static let %s = %s" % (pad, key, swift_string(value)))
    else:
        raise SystemExit("gen_sprites_swift: unsupported layout value for %r: %r" % (key, value))


def const_name(sprite_name: str, sheets_with_name: list) -> str:
    if len(sheets_with_name) == 1:
        return sprite_name
    return None  # handled by caller with a sheet prefix


def generate(spec: dict) -> str:
    L = []
    a = L.append

    a("// Generated by scripts/gen_sprites_swift.py from skinspec/sprites.json.")
    a("// DO NOT EDIT BY HAND - re-run the script instead.")
    a("")
    a("import CoreGraphics")
    a("import Foundation")
    a("")
    a("/// A rectangle in skin pixels, origin top-left, y growing downwards.")
    a("public struct SpriteRect: Equatable, Hashable, Sendable {")
    a("    public let x: Int")
    a("    public let y: Int")
    a("    public let w: Int")
    a("    public let h: Int")
    a("    public init(_ x: Int, _ y: Int, _ w: Int, _ h: Int) { self.x = x; self.y = y; self.w = w; self.h = h }")
    a("    public var cg: CGRect { CGRect(x: CGFloat(x), y: CGFloat(y), width: CGFloat(w), height: CGFloat(h)) }")
    a("    public var origin: CGPoint { CGPoint(x: CGFloat(x), y: CGFloat(y)) }")
    a("    public var size: CGSize { CGSize(width: CGFloat(w), height: CGFloat(h)) }")
    a("    public func offsetBy(_ dx: Int, _ dy: Int) -> SpriteRect { SpriteRect(x + dx, y + dy, w, h) }")
    a("    public func movedTo(_ nx: Int, _ ny: Int) -> SpriteRect { SpriteRect(nx, ny, w, h) }")
    a("    public func contains(_ p: CGPoint) -> Bool { cg.contains(p) }")
    a("}")
    a("")
    a("/// A pair of skin-pixel integers. The accessor you use documents what it means.")
    a("public struct SkinPair: Equatable, Hashable, Sendable {")
    a("    public let a: Int")
    a("    public let b: Int")
    a("    public init(_ a: Int, _ b: Int) { self.a = a; self.b = b }")
    a("    public var x: Int { a }")
    a("    public var y: Int { b }")
    a("    public var w: Int { a }")
    a("    public var h: Int { b }")
    a("    public var lo: Int { a }")
    a("    public var hi: Int { b }")
    a("    /// Travel range length, e.g. volumeThumbTravel.span == 51.")
    a("    public var span: Int { b - a }")
    a("}")
    a("")
    a("public enum SheetID: String, CaseIterable, Sendable {")
    for key, case in SHEET_CASE.items():
        if key in spec["sheets"]:
            a("    case %s = %s" % (case, swift_string(key)))
    a("}")
    a("")
    a("/// Evenly spaced background frames inside a sheet (volume/balance heat ramp, EQ slider wells).")
    a("public struct FrameSpec: Sendable {")
    a("    public let count: Int")
    a("    public let x0: Int")
    a("    public let y0: Int")
    a("    public let strideX: Int")
    a("    public let strideY: Int")
    a("    public let perRow: Int")
    a("    public let w: Int")
    a("    public let h: Int")
    a("    public func rect(_ i: Int) -> SpriteRect {")
    a("        let k = min(max(i, 0), count - 1)")
    a("        let col = perRow > 0 ? k % perRow : 0")
    a("        let row = perRow > 0 ? k / perRow : k")
    a("        return SpriteRect(x0 + strideX * col, y0 + strideY * row, w, h)")
    a("    }")
    a("}")
    a("")
    a("public struct SheetSpec: Sendable {")
    a("    public let id: SheetID")
    a("    public let file: String")
    a("    public let width: Int")
    a("    public let height: Int")
    a("    public let required: Bool")
    a("    public let frames: FrameSpec?")
    a("    /// File stem used for case-insensitive lookup (\"main\" for \"main.bmp\").")
    a("    public var stem: String { String(file.split(separator: \".\").first ?? \"\") }")
    a("}")
    a("")
    a("/// A named rectangle inside a named sheet. This is what renderers ask the skin for.")
    a("public struct SpriteRef: Equatable, Hashable, Sendable {")
    a("    public let sheet: SheetID")
    a("    public let name: String")
    a("    public let rect: SpriteRect")
    a("    public init(_ sheet: SheetID, _ name: String, _ rect: SpriteRect) {")
    a("        self.sheet = sheet; self.name = name; self.rect = rect")
    a("    }")
    a("}")
    a("")

    # ---- sheets ----
    a("public enum SkinSpec {")
    a("    public static let sheetOrder: [SheetID] = [%s]" % ", ".join(
        "." + SHEET_CASE[k] for k in SHEET_CASE if k in spec["sheets"]))
    a("")
    a("    public static let sheets: [SheetID: SheetSpec] = [")
    for key in SHEET_CASE:
        if key not in spec["sheets"]:
            continue
        sh = spec["sheets"][key]
        fr = sh.get("frames")
        if fr:
            frame_lit = ("FrameSpec(count: %d, x0: %d, y0: %d, strideX: %d, strideY: %d, perRow: %d, w: %d, h: %d)"
                         % (fr["count"], fr.get("x0", fr.get("x", 0)), fr.get("y0", fr.get("y", 0)),
                            fr.get("strideX", 0), fr.get("strideY", 0), fr.get("perRow", 1),
                            fr["w"], fr["h"]))
        else:
            frame_lit = "nil"
        a("        .%s: SheetSpec(id: .%s, file: %s, width: %d, height: %d, required: %s, frames: %s),"
          % (SHEET_CASE[key], SHEET_CASE[key], swift_string(sh["file"]), sh["width"], sh["height"],
             "true" if sh.get("required") else "false", frame_lit))
    a("    ]")
    a("")

    # ---- sprite rect table ----
    a("    /// Every sprite rectangle, keyed by sheet then by sprite name.")
    a("    public static let spriteRects: [SheetID: [String: SpriteRect]] = [")
    for key in SHEET_CASE:
        if key not in spec["sheets"]:
            continue
        sprites = spec["sheets"][key].get("sprites")
        if not sprites:
            continue
        a("        .%s: [" % SHEET_CASE[key])
        for name, r in sprites.items():
            a("            %s: SpriteRect(%d, %d, %d, %d)," % ((swift_string(name),) + tuple(r)))
        a("        ],")
    a("    ]")
    a("")
    a("    public static func rect(_ sheet: SheetID, _ name: String) -> SpriteRect? {")
    a("        spriteRects[sheet]?[name]")
    a("    }")
    a("")
    a("    public static func ref(_ sheet: SheetID, _ name: String) -> SpriteRef? {")
    a("        guard let r = rect(sheet, name) else { return nil }")
    a("        return SpriteRef(sheet, name, r)")
    a("    }")
    a("}")
    a("")

    # ---- named sprite constants ----
    owners = {}
    for key, sh in spec["sheets"].items():
        for name in (sh.get("sprites") or {}):
            owners.setdefault(name, []).append(key)

    a("/// Named sprite constants. Where two sheets define the same name (the digit sheets) the")
    a("/// constant carries a sheet prefix; renderers reach the digits through `Skin.digitSprite`.")
    a("public enum Spr {")
    for key in SHEET_CASE:
        if key not in spec["sheets"]:
            continue
        sprites = spec["sheets"][key].get("sprites")
        if not sprites:
            continue
        a("    // %s" % spec["sheets"][key]["file"])
        for name, r in sprites.items():
            cname = name if len(owners[name]) == 1 else "%s_%s" % (key.upper(), name)
            a("    public static let %s = SpriteRef(.%s, %s, SpriteRect(%d, %d, %d, %d))"
              % ((cname, SHEET_CASE[key], swift_string(name)) + tuple(r)))
    a("}")
    a("")

    # ---- layout ----
    a("/// Window layouts: where each sprite is placed inside its window, in skin pixels.")
    a("public enum Layout {")
    for win, enum_name in WINDOW_ENUM.items():
        if win not in spec["layout"]:
            continue
        a("    public enum %s {" % enum_name)
        for k, v in spec["layout"][win].items():
            emit_value(k, v, 8, L)
        a("    }")
        a("")
    L.pop()  # trailing blank line inside the enum
    a("}")
    a("")

    # ---- font ----
    font = spec["font"]
    a("/// The classic 5x6 bitmap font living in text.bmp.")
    a("public enum SkinFontSpec {")
    a("    public static let glyphWidth = %d" % font["glyphWidth"])
    a("    public static let glyphHeight = %d" % font["glyphHeight"])
    a("    public static let columns = %d" % font["columns"])
    a("    public static let rows: [String] = [")
    for row in font["rows"]:
        a("        %s," % swift_string(row))
    a("    ]")
    a("    public static let spaceCell = (row: %d, col: %d)" % (font["space"][0], font["space"][1]))
    a("}")
    a("")
    return "\n".join(L)


def main() -> int:
    with open(SPEC, "r", encoding="utf-8") as fh:
        spec = json.load(fh)
    text = generate(spec)
    check = "--check" in sys.argv[1:]
    old = None
    if os.path.exists(OUT):
        with open(OUT, "r", encoding="utf-8") as fh:
            old = fh.read()
    if check:
        if old != text:
            sys.stderr.write("Sprites.generated.swift is stale; re-run scripts/gen_sprites_swift.py\n")
            return 1
        print("Sprites.generated.swift is up to date")
        return 0
    if old == text:
        print("Sprites.generated.swift unchanged")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s (%d bytes)" % (os.path.relpath(OUT, ROOT), len(text)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
