// Generated by scripts/gen_sprites_swift.py from skinspec/sprites.json.
// DO NOT EDIT BY HAND - re-run the script instead.

import CoreGraphics
import Foundation

/// A rectangle in skin pixels, origin top-left, y growing downwards.
public struct SpriteRect: Equatable, Hashable, Sendable {
    public let x: Int
    public let y: Int
    public let w: Int
    public let h: Int
    public init(_ x: Int, _ y: Int, _ w: Int, _ h: Int) { self.x = x; self.y = y; self.w = w; self.h = h }
    public var cg: CGRect { CGRect(x: CGFloat(x), y: CGFloat(y), width: CGFloat(w), height: CGFloat(h)) }
    public var origin: CGPoint { CGPoint(x: CGFloat(x), y: CGFloat(y)) }
    public var size: CGSize { CGSize(width: CGFloat(w), height: CGFloat(h)) }
    public func offsetBy(_ dx: Int, _ dy: Int) -> SpriteRect { SpriteRect(x + dx, y + dy, w, h) }
    public func movedTo(_ nx: Int, _ ny: Int) -> SpriteRect { SpriteRect(nx, ny, w, h) }
    public func contains(_ p: CGPoint) -> Bool { cg.contains(p) }
}

/// A pair of skin-pixel integers. The accessor you use documents what it means.
public struct SkinPair: Equatable, Hashable, Sendable {
    public let a: Int
    public let b: Int
    public init(_ a: Int, _ b: Int) { self.a = a; self.b = b }
    public var x: Int { a }
    public var y: Int { b }
    public var w: Int { a }
    public var h: Int { b }
    public var lo: Int { a }
    public var hi: Int { b }
    /// Travel range length, e.g. volumeThumbTravel.span == 51.
    public var span: Int { b - a }
}

public enum SheetID: String, CaseIterable, Sendable {
    case main = "main"
    case titlebar = "titlebar"
    case cbuttons = "cbuttons"
    case shufrep = "shufrep"
    case posbar = "posbar"
    case volume = "volume"
    case balance = "balance"
    case monoster = "monoster"
    case playpaus = "playpaus"
    case numbers = "numbers"
    case numsEx = "nums_ex"
    case text = "text"
    case eqmain = "eqmain"
    case pledit = "pledit"
}

/// Evenly spaced background frames inside a sheet (volume/balance heat ramp, EQ slider wells).
public struct FrameSpec: Sendable {
    public let count: Int
    public let x0: Int
    public let y0: Int
    public let strideX: Int
    public let strideY: Int
    public let perRow: Int
    public let w: Int
    public let h: Int
    public func rect(_ i: Int) -> SpriteRect {
        let k = min(max(i, 0), count - 1)
        let col = perRow > 0 ? k % perRow : 0
        let row = perRow > 0 ? k / perRow : k
        return SpriteRect(x0 + strideX * col, y0 + strideY * row, w, h)
    }
}

public struct SheetSpec: Sendable {
    public let id: SheetID
    public let file: String
    public let width: Int
    public let height: Int
    public let required: Bool
    public let frames: FrameSpec?
    /// File stem used for case-insensitive lookup ("main" for "main.bmp").
    public var stem: String { String(file.split(separator: ".").first ?? "") }
}

/// A named rectangle inside a named sheet. This is what renderers ask the skin for.
public struct SpriteRef: Equatable, Hashable, Sendable {
    public let sheet: SheetID
    public let name: String
    public let rect: SpriteRect
    public init(_ sheet: SheetID, _ name: String, _ rect: SpriteRect) {
        self.sheet = sheet; self.name = name; self.rect = rect
    }
}

public enum SkinSpec {
    public static let sheetOrder: [SheetID] = [.main, .titlebar, .cbuttons, .shufrep, .posbar, .volume, .balance, .monoster, .playpaus, .numbers, .numsEx, .text, .eqmain, .pledit]

    public static let sheets: [SheetID: SheetSpec] = [
        .main: SheetSpec(id: .main, file: "main.bmp", width: 275, height: 116, required: true, frames: nil),
        .titlebar: SheetSpec(id: .titlebar, file: "titlebar.bmp", width: 344, height: 87, required: true, frames: nil),
        .cbuttons: SheetSpec(id: .cbuttons, file: "cbuttons.bmp", width: 136, height: 36, required: true, frames: nil),
        .shufrep: SheetSpec(id: .shufrep, file: "shufrep.bmp", width: 92, height: 85, required: true, frames: nil),
        .posbar: SheetSpec(id: .posbar, file: "posbar.bmp", width: 307, height: 10, required: true, frames: nil),
        .volume: SheetSpec(id: .volume, file: "volume.bmp", width: 68, height: 433, required: true, frames: FrameSpec(count: 28, x0: 0, y0: 0, strideX: 0, strideY: 15, perRow: 1, w: 68, h: 13)),
        .balance: SheetSpec(id: .balance, file: "balance.bmp", width: 68, height: 433, required: true, frames: FrameSpec(count: 28, x0: 9, y0: 0, strideX: 0, strideY: 15, perRow: 1, w: 38, h: 13)),
        .monoster: SheetSpec(id: .monoster, file: "monoster.bmp", width: 58, height: 24, required: true, frames: nil),
        .playpaus: SheetSpec(id: .playpaus, file: "playpaus.bmp", width: 42, height: 9, required: true, frames: nil),
        .numbers: SheetSpec(id: .numbers, file: "numbers.bmp", width: 99, height: 13, required: false, frames: nil),
        .numsEx: SheetSpec(id: .numsEx, file: "nums_ex.bmp", width: 108, height: 13, required: false, frames: nil),
        .text: SheetSpec(id: .text, file: "text.bmp", width: 155, height: 74, required: true, frames: nil),
        .eqmain: SheetSpec(id: .eqmain, file: "eqmain.bmp", width: 275, height: 315, required: false, frames: FrameSpec(count: 28, x0: 13, y0: 164, strideX: 15, strideY: 65, perRow: 14, w: 14, h: 63)),
        .pledit: SheetSpec(id: .pledit, file: "pledit.bmp", width: 280, height: 186, required: false, frames: nil),
    ]

    /// Every sprite rectangle, keyed by sheet then by sprite name.
    public static let spriteRects: [SheetID: [String: SpriteRect]] = [
        .main: [
            "MAIN_WINDOW_BACKGROUND": SpriteRect(0, 0, 275, 116),
        ],
        .titlebar: [
            "MAIN_TITLE_BAR_SELECTED": SpriteRect(27, 0, 275, 14),
            "MAIN_TITLE_BAR": SpriteRect(27, 15, 275, 14),
            "MAIN_SHADE_BACKGROUND_SELECTED": SpriteRect(27, 29, 275, 14),
            "MAIN_SHADE_BACKGROUND": SpriteRect(27, 42, 275, 14),
            "MAIN_EASTER_EGG_TITLE_BAR_SELECTED": SpriteRect(27, 57, 275, 14),
            "MAIN_EASTER_EGG_TITLE_BAR": SpriteRect(27, 72, 275, 14),
            "MAIN_OPTIONS_BUTTON": SpriteRect(0, 0, 9, 9),
            "MAIN_OPTIONS_BUTTON_DEPRESSED": SpriteRect(0, 9, 9, 9),
            "MAIN_MINIMIZE_BUTTON": SpriteRect(9, 0, 9, 9),
            "MAIN_MINIMIZE_BUTTON_DEPRESSED": SpriteRect(9, 9, 9, 9),
            "MAIN_CLOSE_BUTTON": SpriteRect(18, 0, 9, 9),
            "MAIN_CLOSE_BUTTON_DEPRESSED": SpriteRect(18, 9, 9, 9),
            "MAIN_SHADE_BUTTON": SpriteRect(0, 18, 9, 9),
            "MAIN_SHADE_BUTTON_DEPRESSED": SpriteRect(9, 18, 9, 9),
            "MAIN_SHADE_BUTTON_SELECTED": SpriteRect(0, 27, 9, 9),
            "MAIN_SHADE_BUTTON_SELECTED_DEPRESSED": SpriteRect(9, 27, 9, 9),
            "MAIN_SHADE_POSITION_BACKGROUND": SpriteRect(0, 36, 17, 7),
            "MAIN_SHADE_POSITION_THUMB_LEFT": SpriteRect(17, 36, 3, 7),
            "MAIN_SHADE_POSITION_THUMB": SpriteRect(20, 36, 3, 7),
            "MAIN_SHADE_POSITION_THUMB_RIGHT": SpriteRect(23, 36, 3, 7),
            "MAIN_CLUTTER_BAR_BACKGROUND": SpriteRect(304, 0, 8, 43),
            "MAIN_CLUTTER_BAR_BACKGROUND_DISABLED": SpriteRect(312, 0, 8, 43),
            "MAIN_CLUTTER_BAR_BUTTON_O_SELECTED": SpriteRect(304, 47, 8, 8),
            "MAIN_CLUTTER_BAR_BUTTON_A_SELECTED": SpriteRect(312, 55, 8, 7),
            "MAIN_CLUTTER_BAR_BUTTON_I_SELECTED": SpriteRect(320, 62, 8, 7),
            "MAIN_CLUTTER_BAR_BUTTON_D_SELECTED": SpriteRect(328, 69, 8, 8),
            "MAIN_CLUTTER_BAR_BUTTON_V_SELECTED": SpriteRect(336, 77, 8, 7),
        ],
        .cbuttons: [
            "MAIN_PREVIOUS_BUTTON": SpriteRect(0, 0, 23, 18),
            "MAIN_PREVIOUS_BUTTON_ACTIVE": SpriteRect(0, 18, 23, 18),
            "MAIN_PLAY_BUTTON": SpriteRect(23, 0, 23, 18),
            "MAIN_PLAY_BUTTON_ACTIVE": SpriteRect(23, 18, 23, 18),
            "MAIN_PAUSE_BUTTON": SpriteRect(46, 0, 23, 18),
            "MAIN_PAUSE_BUTTON_ACTIVE": SpriteRect(46, 18, 23, 18),
            "MAIN_STOP_BUTTON": SpriteRect(69, 0, 23, 18),
            "MAIN_STOP_BUTTON_ACTIVE": SpriteRect(69, 18, 23, 18),
            "MAIN_NEXT_BUTTON": SpriteRect(92, 0, 22, 18),
            "MAIN_NEXT_BUTTON_ACTIVE": SpriteRect(92, 18, 22, 18),
            "MAIN_EJECT_BUTTON": SpriteRect(114, 0, 22, 16),
            "MAIN_EJECT_BUTTON_ACTIVE": SpriteRect(114, 16, 22, 16),
        ],
        .shufrep: [
            "MAIN_REPEAT_BUTTON": SpriteRect(0, 0, 28, 15),
            "MAIN_REPEAT_BUTTON_DEPRESSED": SpriteRect(0, 15, 28, 15),
            "MAIN_REPEAT_BUTTON_SELECTED": SpriteRect(0, 30, 28, 15),
            "MAIN_REPEAT_BUTTON_SELECTED_DEPRESSED": SpriteRect(0, 45, 28, 15),
            "MAIN_SHUFFLE_BUTTON": SpriteRect(28, 0, 47, 15),
            "MAIN_SHUFFLE_BUTTON_DEPRESSED": SpriteRect(28, 15, 47, 15),
            "MAIN_SHUFFLE_BUTTON_SELECTED": SpriteRect(28, 30, 47, 15),
            "MAIN_SHUFFLE_BUTTON_SELECTED_DEPRESSED": SpriteRect(28, 45, 47, 15),
            "MAIN_EQ_BUTTON": SpriteRect(0, 61, 23, 12),
            "MAIN_EQ_BUTTON_SELECTED": SpriteRect(0, 73, 23, 12),
            "MAIN_EQ_BUTTON_DEPRESSED": SpriteRect(46, 61, 23, 12),
            "MAIN_EQ_BUTTON_DEPRESSED_SELECTED": SpriteRect(46, 73, 23, 12),
            "MAIN_PLAYLIST_BUTTON": SpriteRect(23, 61, 23, 12),
            "MAIN_PLAYLIST_BUTTON_SELECTED": SpriteRect(23, 73, 23, 12),
            "MAIN_PLAYLIST_BUTTON_DEPRESSED": SpriteRect(69, 61, 23, 12),
            "MAIN_PLAYLIST_BUTTON_DEPRESSED_SELECTED": SpriteRect(69, 73, 23, 12),
        ],
        .posbar: [
            "MAIN_POSITION_SLIDER_BACKGROUND": SpriteRect(0, 0, 248, 10),
            "MAIN_POSITION_SLIDER_THUMB": SpriteRect(248, 0, 29, 10),
            "MAIN_POSITION_SLIDER_THUMB_SELECTED": SpriteRect(278, 0, 29, 10),
        ],
        .volume: [
            "MAIN_VOLUME_THUMB_SELECTED": SpriteRect(0, 422, 14, 11),
            "MAIN_VOLUME_THUMB": SpriteRect(15, 422, 14, 11),
        ],
        .balance: [
            "MAIN_BALANCE_THUMB_SELECTED": SpriteRect(0, 422, 14, 11),
            "MAIN_BALANCE_THUMB": SpriteRect(15, 422, 14, 11),
        ],
        .monoster: [
            "MAIN_STEREO_SELECTED": SpriteRect(0, 0, 29, 12),
            "MAIN_STEREO": SpriteRect(0, 12, 29, 12),
            "MAIN_MONO_SELECTED": SpriteRect(29, 0, 27, 12),
            "MAIN_MONO": SpriteRect(29, 12, 27, 12),
        ],
        .playpaus: [
            "MAIN_PLAYING_INDICATOR": SpriteRect(0, 0, 9, 9),
            "MAIN_PAUSED_INDICATOR": SpriteRect(9, 0, 9, 9),
            "MAIN_STOPPED_INDICATOR": SpriteRect(18, 0, 9, 9),
            "MAIN_NOT_WORKING_INDICATOR": SpriteRect(36, 0, 3, 9),
            "MAIN_WORKING_INDICATOR": SpriteRect(39, 0, 3, 9),
        ],
        .numbers: [
            "DIGIT_0": SpriteRect(0, 0, 9, 13),
            "DIGIT_1": SpriteRect(9, 0, 9, 13),
            "DIGIT_2": SpriteRect(18, 0, 9, 13),
            "DIGIT_3": SpriteRect(27, 0, 9, 13),
            "DIGIT_4": SpriteRect(36, 0, 9, 13),
            "DIGIT_5": SpriteRect(45, 0, 9, 13),
            "DIGIT_6": SpriteRect(54, 0, 9, 13),
            "DIGIT_7": SpriteRect(63, 0, 9, 13),
            "DIGIT_8": SpriteRect(72, 0, 9, 13),
            "DIGIT_9": SpriteRect(81, 0, 9, 13),
            "DIGIT_BLANK": SpriteRect(90, 0, 9, 13),
            "NO_MINUS_SIGN": SpriteRect(9, 6, 5, 1),
            "MINUS_SIGN": SpriteRect(20, 6, 5, 1),
        ],
        .numsEx: [
            "DIGIT_0": SpriteRect(0, 0, 9, 13),
            "DIGIT_1": SpriteRect(9, 0, 9, 13),
            "DIGIT_2": SpriteRect(18, 0, 9, 13),
            "DIGIT_3": SpriteRect(27, 0, 9, 13),
            "DIGIT_4": SpriteRect(36, 0, 9, 13),
            "DIGIT_5": SpriteRect(45, 0, 9, 13),
            "DIGIT_6": SpriteRect(54, 0, 9, 13),
            "DIGIT_7": SpriteRect(63, 0, 9, 13),
            "DIGIT_8": SpriteRect(72, 0, 9, 13),
            "DIGIT_9": SpriteRect(81, 0, 9, 13),
            "DIGIT_BLANK": SpriteRect(90, 0, 9, 13),
            "DIGIT_MINUS": SpriteRect(99, 0, 9, 13),
        ],
        .eqmain: [
            "EQ_WINDOW_BACKGROUND": SpriteRect(0, 0, 275, 116),
            "EQ_TITLE_BAR_SELECTED": SpriteRect(0, 134, 275, 14),
            "EQ_TITLE_BAR": SpriteRect(0, 149, 275, 14),
            "EQ_CLOSE_BUTTON": SpriteRect(0, 116, 9, 9),
            "EQ_CLOSE_BUTTON_ACTIVE": SpriteRect(0, 125, 9, 9),
            "EQ_ON_BUTTON": SpriteRect(10, 119, 26, 12),
            "EQ_ON_BUTTON_DEPRESSED": SpriteRect(128, 119, 26, 12),
            "EQ_ON_BUTTON_SELECTED": SpriteRect(69, 119, 26, 12),
            "EQ_ON_BUTTON_SELECTED_DEPRESSED": SpriteRect(187, 119, 26, 12),
            "EQ_AUTO_BUTTON": SpriteRect(36, 119, 32, 12),
            "EQ_AUTO_BUTTON_DEPRESSED": SpriteRect(154, 119, 32, 12),
            "EQ_AUTO_BUTTON_SELECTED": SpriteRect(95, 119, 32, 12),
            "EQ_AUTO_BUTTON_SELECTED_DEPRESSED": SpriteRect(213, 119, 32, 12),
            "EQ_SLIDER_THUMB": SpriteRect(0, 164, 11, 11),
            "EQ_SLIDER_THUMB_SELECTED": SpriteRect(0, 176, 11, 11),
            "EQ_PRESETS_BUTTON": SpriteRect(224, 164, 44, 12),
            "EQ_PRESETS_BUTTON_SELECTED": SpriteRect(224, 176, 44, 12),
            "EQ_GRAPH_BACKGROUND": SpriteRect(0, 294, 113, 19),
            "EQ_GRAPH_LINE_COLORS": SpriteRect(115, 294, 1, 19),
            "EQ_PREAMP_LINE": SpriteRect(0, 314, 113, 1),
        ],
        .pledit: [
            "PLAYLIST_TOP_LEFT_SELECTED": SpriteRect(0, 0, 25, 20),
            "PLAYLIST_TITLE_BAR_SELECTED": SpriteRect(26, 0, 100, 20),
            "PLAYLIST_TOP_TILE_SELECTED": SpriteRect(127, 0, 25, 20),
            "PLAYLIST_TOP_RIGHT_CORNER_SELECTED": SpriteRect(153, 0, 25, 20),
            "PLAYLIST_TOP_LEFT_CORNER": SpriteRect(0, 21, 25, 20),
            "PLAYLIST_TITLE_BAR": SpriteRect(26, 21, 100, 20),
            "PLAYLIST_TOP_TILE": SpriteRect(127, 21, 25, 20),
            "PLAYLIST_TOP_RIGHT_CORNER": SpriteRect(153, 21, 25, 20),
            "PLAYLIST_LEFT_TILE": SpriteRect(0, 42, 12, 29),
            "PLAYLIST_RIGHT_TILE": SpriteRect(31, 42, 20, 29),
            "PLAYLIST_BOTTOM_TILE": SpriteRect(179, 0, 25, 38),
            "PLAYLIST_BOTTOM_LEFT_CORNER": SpriteRect(0, 72, 125, 38),
            "PLAYLIST_BOTTOM_RIGHT_CORNER": SpriteRect(126, 72, 150, 38),
            "PLAYLIST_VISUALIZER_BACKGROUND": SpriteRect(205, 0, 75, 38),
            "PLAYLIST_SCROLL_HANDLE": SpriteRect(52, 53, 8, 18),
            "PLAYLIST_SCROLL_HANDLE_SELECTED": SpriteRect(61, 53, 8, 18),
            "PLAYLIST_CLOSE_SELECTED": SpriteRect(52, 42, 9, 9),
            "PLAYLIST_COLLAPSE_SELECTED": SpriteRect(62, 42, 9, 9),
        ],
    ]

    public static func rect(_ sheet: SheetID, _ name: String) -> SpriteRect? {
        spriteRects[sheet]?[name]
    }

    public static func ref(_ sheet: SheetID, _ name: String) -> SpriteRef? {
        guard let r = rect(sheet, name) else { return nil }
        return SpriteRef(sheet, name, r)
    }
}

/// Named sprite constants. Where two sheets define the same name (the digit sheets) the
/// constant carries a sheet prefix; renderers reach the digits through `Skin.digitSprite`.
public enum Spr {
    // main.bmp
    public static let MAIN_WINDOW_BACKGROUND = SpriteRef(.main, "MAIN_WINDOW_BACKGROUND", SpriteRect(0, 0, 275, 116))
    // titlebar.bmp
    public static let MAIN_TITLE_BAR_SELECTED = SpriteRef(.titlebar, "MAIN_TITLE_BAR_SELECTED", SpriteRect(27, 0, 275, 14))
    public static let MAIN_TITLE_BAR = SpriteRef(.titlebar, "MAIN_TITLE_BAR", SpriteRect(27, 15, 275, 14))
    public static let MAIN_SHADE_BACKGROUND_SELECTED = SpriteRef(.titlebar, "MAIN_SHADE_BACKGROUND_SELECTED", SpriteRect(27, 29, 275, 14))
    public static let MAIN_SHADE_BACKGROUND = SpriteRef(.titlebar, "MAIN_SHADE_BACKGROUND", SpriteRect(27, 42, 275, 14))
    public static let MAIN_EASTER_EGG_TITLE_BAR_SELECTED = SpriteRef(.titlebar, "MAIN_EASTER_EGG_TITLE_BAR_SELECTED", SpriteRect(27, 57, 275, 14))
    public static let MAIN_EASTER_EGG_TITLE_BAR = SpriteRef(.titlebar, "MAIN_EASTER_EGG_TITLE_BAR", SpriteRect(27, 72, 275, 14))
    public static let MAIN_OPTIONS_BUTTON = SpriteRef(.titlebar, "MAIN_OPTIONS_BUTTON", SpriteRect(0, 0, 9, 9))
    public static let MAIN_OPTIONS_BUTTON_DEPRESSED = SpriteRef(.titlebar, "MAIN_OPTIONS_BUTTON_DEPRESSED", SpriteRect(0, 9, 9, 9))
    public static let MAIN_MINIMIZE_BUTTON = SpriteRef(.titlebar, "MAIN_MINIMIZE_BUTTON", SpriteRect(9, 0, 9, 9))
    public static let MAIN_MINIMIZE_BUTTON_DEPRESSED = SpriteRef(.titlebar, "MAIN_MINIMIZE_BUTTON_DEPRESSED", SpriteRect(9, 9, 9, 9))
    public static let MAIN_CLOSE_BUTTON = SpriteRef(.titlebar, "MAIN_CLOSE_BUTTON", SpriteRect(18, 0, 9, 9))
    public static let MAIN_CLOSE_BUTTON_DEPRESSED = SpriteRef(.titlebar, "MAIN_CLOSE_BUTTON_DEPRESSED", SpriteRect(18, 9, 9, 9))
    public static let MAIN_SHADE_BUTTON = SpriteRef(.titlebar, "MAIN_SHADE_BUTTON", SpriteRect(0, 18, 9, 9))
    public static let MAIN_SHADE_BUTTON_DEPRESSED = SpriteRef(.titlebar, "MAIN_SHADE_BUTTON_DEPRESSED", SpriteRect(9, 18, 9, 9))
    public static let MAIN_SHADE_BUTTON_SELECTED = SpriteRef(.titlebar, "MAIN_SHADE_BUTTON_SELECTED", SpriteRect(0, 27, 9, 9))
    public static let MAIN_SHADE_BUTTON_SELECTED_DEPRESSED = SpriteRef(.titlebar, "MAIN_SHADE_BUTTON_SELECTED_DEPRESSED", SpriteRect(9, 27, 9, 9))
    public static let MAIN_SHADE_POSITION_BACKGROUND = SpriteRef(.titlebar, "MAIN_SHADE_POSITION_BACKGROUND", SpriteRect(0, 36, 17, 7))
    public static let MAIN_SHADE_POSITION_THUMB_LEFT = SpriteRef(.titlebar, "MAIN_SHADE_POSITION_THUMB_LEFT", SpriteRect(17, 36, 3, 7))
    public static let MAIN_SHADE_POSITION_THUMB = SpriteRef(.titlebar, "MAIN_SHADE_POSITION_THUMB", SpriteRect(20, 36, 3, 7))
    public static let MAIN_SHADE_POSITION_THUMB_RIGHT = SpriteRef(.titlebar, "MAIN_SHADE_POSITION_THUMB_RIGHT", SpriteRect(23, 36, 3, 7))
    public static let MAIN_CLUTTER_BAR_BACKGROUND = SpriteRef(.titlebar, "MAIN_CLUTTER_BAR_BACKGROUND", SpriteRect(304, 0, 8, 43))
    public static let MAIN_CLUTTER_BAR_BACKGROUND_DISABLED = SpriteRef(.titlebar, "MAIN_CLUTTER_BAR_BACKGROUND_DISABLED", SpriteRect(312, 0, 8, 43))
    public static let MAIN_CLUTTER_BAR_BUTTON_O_SELECTED = SpriteRef(.titlebar, "MAIN_CLUTTER_BAR_BUTTON_O_SELECTED", SpriteRect(304, 47, 8, 8))
    public static let MAIN_CLUTTER_BAR_BUTTON_A_SELECTED = SpriteRef(.titlebar, "MAIN_CLUTTER_BAR_BUTTON_A_SELECTED", SpriteRect(312, 55, 8, 7))
    public static let MAIN_CLUTTER_BAR_BUTTON_I_SELECTED = SpriteRef(.titlebar, "MAIN_CLUTTER_BAR_BUTTON_I_SELECTED", SpriteRect(320, 62, 8, 7))
    public static let MAIN_CLUTTER_BAR_BUTTON_D_SELECTED = SpriteRef(.titlebar, "MAIN_CLUTTER_BAR_BUTTON_D_SELECTED", SpriteRect(328, 69, 8, 8))
    public static let MAIN_CLUTTER_BAR_BUTTON_V_SELECTED = SpriteRef(.titlebar, "MAIN_CLUTTER_BAR_BUTTON_V_SELECTED", SpriteRect(336, 77, 8, 7))
    // cbuttons.bmp
    public static let MAIN_PREVIOUS_BUTTON = SpriteRef(.cbuttons, "MAIN_PREVIOUS_BUTTON", SpriteRect(0, 0, 23, 18))
    public static let MAIN_PREVIOUS_BUTTON_ACTIVE = SpriteRef(.cbuttons, "MAIN_PREVIOUS_BUTTON_ACTIVE", SpriteRect(0, 18, 23, 18))
    public static let MAIN_PLAY_BUTTON = SpriteRef(.cbuttons, "MAIN_PLAY_BUTTON", SpriteRect(23, 0, 23, 18))
    public static let MAIN_PLAY_BUTTON_ACTIVE = SpriteRef(.cbuttons, "MAIN_PLAY_BUTTON_ACTIVE", SpriteRect(23, 18, 23, 18))
    public static let MAIN_PAUSE_BUTTON = SpriteRef(.cbuttons, "MAIN_PAUSE_BUTTON", SpriteRect(46, 0, 23, 18))
    public static let MAIN_PAUSE_BUTTON_ACTIVE = SpriteRef(.cbuttons, "MAIN_PAUSE_BUTTON_ACTIVE", SpriteRect(46, 18, 23, 18))
    public static let MAIN_STOP_BUTTON = SpriteRef(.cbuttons, "MAIN_STOP_BUTTON", SpriteRect(69, 0, 23, 18))
    public static let MAIN_STOP_BUTTON_ACTIVE = SpriteRef(.cbuttons, "MAIN_STOP_BUTTON_ACTIVE", SpriteRect(69, 18, 23, 18))
    public static let MAIN_NEXT_BUTTON = SpriteRef(.cbuttons, "MAIN_NEXT_BUTTON", SpriteRect(92, 0, 22, 18))
    public static let MAIN_NEXT_BUTTON_ACTIVE = SpriteRef(.cbuttons, "MAIN_NEXT_BUTTON_ACTIVE", SpriteRect(92, 18, 22, 18))
    public static let MAIN_EJECT_BUTTON = SpriteRef(.cbuttons, "MAIN_EJECT_BUTTON", SpriteRect(114, 0, 22, 16))
    public static let MAIN_EJECT_BUTTON_ACTIVE = SpriteRef(.cbuttons, "MAIN_EJECT_BUTTON_ACTIVE", SpriteRect(114, 16, 22, 16))
    // shufrep.bmp
    public static let MAIN_REPEAT_BUTTON = SpriteRef(.shufrep, "MAIN_REPEAT_BUTTON", SpriteRect(0, 0, 28, 15))
    public static let MAIN_REPEAT_BUTTON_DEPRESSED = SpriteRef(.shufrep, "MAIN_REPEAT_BUTTON_DEPRESSED", SpriteRect(0, 15, 28, 15))
    public static let MAIN_REPEAT_BUTTON_SELECTED = SpriteRef(.shufrep, "MAIN_REPEAT_BUTTON_SELECTED", SpriteRect(0, 30, 28, 15))
    public static let MAIN_REPEAT_BUTTON_SELECTED_DEPRESSED = SpriteRef(.shufrep, "MAIN_REPEAT_BUTTON_SELECTED_DEPRESSED", SpriteRect(0, 45, 28, 15))
    public static let MAIN_SHUFFLE_BUTTON = SpriteRef(.shufrep, "MAIN_SHUFFLE_BUTTON", SpriteRect(28, 0, 47, 15))
    public static let MAIN_SHUFFLE_BUTTON_DEPRESSED = SpriteRef(.shufrep, "MAIN_SHUFFLE_BUTTON_DEPRESSED", SpriteRect(28, 15, 47, 15))
    public static let MAIN_SHUFFLE_BUTTON_SELECTED = SpriteRef(.shufrep, "MAIN_SHUFFLE_BUTTON_SELECTED", SpriteRect(28, 30, 47, 15))
    public static let MAIN_SHUFFLE_BUTTON_SELECTED_DEPRESSED = SpriteRef(.shufrep, "MAIN_SHUFFLE_BUTTON_SELECTED_DEPRESSED", SpriteRect(28, 45, 47, 15))
    public static let MAIN_EQ_BUTTON = SpriteRef(.shufrep, "MAIN_EQ_BUTTON", SpriteRect(0, 61, 23, 12))
    public static let MAIN_EQ_BUTTON_SELECTED = SpriteRef(.shufrep, "MAIN_EQ_BUTTON_SELECTED", SpriteRect(0, 73, 23, 12))
    public static let MAIN_EQ_BUTTON_DEPRESSED = SpriteRef(.shufrep, "MAIN_EQ_BUTTON_DEPRESSED", SpriteRect(46, 61, 23, 12))
    public static let MAIN_EQ_BUTTON_DEPRESSED_SELECTED = SpriteRef(.shufrep, "MAIN_EQ_BUTTON_DEPRESSED_SELECTED", SpriteRect(46, 73, 23, 12))
    public static let MAIN_PLAYLIST_BUTTON = SpriteRef(.shufrep, "MAIN_PLAYLIST_BUTTON", SpriteRect(23, 61, 23, 12))
    public static let MAIN_PLAYLIST_BUTTON_SELECTED = SpriteRef(.shufrep, "MAIN_PLAYLIST_BUTTON_SELECTED", SpriteRect(23, 73, 23, 12))
    public static let MAIN_PLAYLIST_BUTTON_DEPRESSED = SpriteRef(.shufrep, "MAIN_PLAYLIST_BUTTON_DEPRESSED", SpriteRect(69, 61, 23, 12))
    public static let MAIN_PLAYLIST_BUTTON_DEPRESSED_SELECTED = SpriteRef(.shufrep, "MAIN_PLAYLIST_BUTTON_DEPRESSED_SELECTED", SpriteRect(69, 73, 23, 12))
    // posbar.bmp
    public static let MAIN_POSITION_SLIDER_BACKGROUND = SpriteRef(.posbar, "MAIN_POSITION_SLIDER_BACKGROUND", SpriteRect(0, 0, 248, 10))
    public static let MAIN_POSITION_SLIDER_THUMB = SpriteRef(.posbar, "MAIN_POSITION_SLIDER_THUMB", SpriteRect(248, 0, 29, 10))
    public static let MAIN_POSITION_SLIDER_THUMB_SELECTED = SpriteRef(.posbar, "MAIN_POSITION_SLIDER_THUMB_SELECTED", SpriteRect(278, 0, 29, 10))
    // volume.bmp
    public static let MAIN_VOLUME_THUMB_SELECTED = SpriteRef(.volume, "MAIN_VOLUME_THUMB_SELECTED", SpriteRect(0, 422, 14, 11))
    public static let MAIN_VOLUME_THUMB = SpriteRef(.volume, "MAIN_VOLUME_THUMB", SpriteRect(15, 422, 14, 11))
    // balance.bmp
    public static let MAIN_BALANCE_THUMB_SELECTED = SpriteRef(.balance, "MAIN_BALANCE_THUMB_SELECTED", SpriteRect(0, 422, 14, 11))
    public static let MAIN_BALANCE_THUMB = SpriteRef(.balance, "MAIN_BALANCE_THUMB", SpriteRect(15, 422, 14, 11))
    // monoster.bmp
    public static let MAIN_STEREO_SELECTED = SpriteRef(.monoster, "MAIN_STEREO_SELECTED", SpriteRect(0, 0, 29, 12))
    public static let MAIN_STEREO = SpriteRef(.monoster, "MAIN_STEREO", SpriteRect(0, 12, 29, 12))
    public static let MAIN_MONO_SELECTED = SpriteRef(.monoster, "MAIN_MONO_SELECTED", SpriteRect(29, 0, 27, 12))
    public static let MAIN_MONO = SpriteRef(.monoster, "MAIN_MONO", SpriteRect(29, 12, 27, 12))
    // playpaus.bmp
    public static let MAIN_PLAYING_INDICATOR = SpriteRef(.playpaus, "MAIN_PLAYING_INDICATOR", SpriteRect(0, 0, 9, 9))
    public static let MAIN_PAUSED_INDICATOR = SpriteRef(.playpaus, "MAIN_PAUSED_INDICATOR", SpriteRect(9, 0, 9, 9))
    public static let MAIN_STOPPED_INDICATOR = SpriteRef(.playpaus, "MAIN_STOPPED_INDICATOR", SpriteRect(18, 0, 9, 9))
    public static let MAIN_NOT_WORKING_INDICATOR = SpriteRef(.playpaus, "MAIN_NOT_WORKING_INDICATOR", SpriteRect(36, 0, 3, 9))
    public static let MAIN_WORKING_INDICATOR = SpriteRef(.playpaus, "MAIN_WORKING_INDICATOR", SpriteRect(39, 0, 3, 9))
    // numbers.bmp
    public static let NUMBERS_DIGIT_0 = SpriteRef(.numbers, "DIGIT_0", SpriteRect(0, 0, 9, 13))
    public static let NUMBERS_DIGIT_1 = SpriteRef(.numbers, "DIGIT_1", SpriteRect(9, 0, 9, 13))
    public static let NUMBERS_DIGIT_2 = SpriteRef(.numbers, "DIGIT_2", SpriteRect(18, 0, 9, 13))
    public static let NUMBERS_DIGIT_3 = SpriteRef(.numbers, "DIGIT_3", SpriteRect(27, 0, 9, 13))
    public static let NUMBERS_DIGIT_4 = SpriteRef(.numbers, "DIGIT_4", SpriteRect(36, 0, 9, 13))
    public static let NUMBERS_DIGIT_5 = SpriteRef(.numbers, "DIGIT_5", SpriteRect(45, 0, 9, 13))
    public static let NUMBERS_DIGIT_6 = SpriteRef(.numbers, "DIGIT_6", SpriteRect(54, 0, 9, 13))
    public static let NUMBERS_DIGIT_7 = SpriteRef(.numbers, "DIGIT_7", SpriteRect(63, 0, 9, 13))
    public static let NUMBERS_DIGIT_8 = SpriteRef(.numbers, "DIGIT_8", SpriteRect(72, 0, 9, 13))
    public static let NUMBERS_DIGIT_9 = SpriteRef(.numbers, "DIGIT_9", SpriteRect(81, 0, 9, 13))
    public static let NUMBERS_DIGIT_BLANK = SpriteRef(.numbers, "DIGIT_BLANK", SpriteRect(90, 0, 9, 13))
    public static let NO_MINUS_SIGN = SpriteRef(.numbers, "NO_MINUS_SIGN", SpriteRect(9, 6, 5, 1))
    public static let MINUS_SIGN = SpriteRef(.numbers, "MINUS_SIGN", SpriteRect(20, 6, 5, 1))
    // nums_ex.bmp
    public static let NUMS_EX_DIGIT_0 = SpriteRef(.numsEx, "DIGIT_0", SpriteRect(0, 0, 9, 13))
    public static let NUMS_EX_DIGIT_1 = SpriteRef(.numsEx, "DIGIT_1", SpriteRect(9, 0, 9, 13))
    public static let NUMS_EX_DIGIT_2 = SpriteRef(.numsEx, "DIGIT_2", SpriteRect(18, 0, 9, 13))
    public static let NUMS_EX_DIGIT_3 = SpriteRef(.numsEx, "DIGIT_3", SpriteRect(27, 0, 9, 13))
    public static let NUMS_EX_DIGIT_4 = SpriteRef(.numsEx, "DIGIT_4", SpriteRect(36, 0, 9, 13))
    public static let NUMS_EX_DIGIT_5 = SpriteRef(.numsEx, "DIGIT_5", SpriteRect(45, 0, 9, 13))
    public static let NUMS_EX_DIGIT_6 = SpriteRef(.numsEx, "DIGIT_6", SpriteRect(54, 0, 9, 13))
    public static let NUMS_EX_DIGIT_7 = SpriteRef(.numsEx, "DIGIT_7", SpriteRect(63, 0, 9, 13))
    public static let NUMS_EX_DIGIT_8 = SpriteRef(.numsEx, "DIGIT_8", SpriteRect(72, 0, 9, 13))
    public static let NUMS_EX_DIGIT_9 = SpriteRef(.numsEx, "DIGIT_9", SpriteRect(81, 0, 9, 13))
    public static let NUMS_EX_DIGIT_BLANK = SpriteRef(.numsEx, "DIGIT_BLANK", SpriteRect(90, 0, 9, 13))
    public static let DIGIT_MINUS = SpriteRef(.numsEx, "DIGIT_MINUS", SpriteRect(99, 0, 9, 13))
    // eqmain.bmp
    public static let EQ_WINDOW_BACKGROUND = SpriteRef(.eqmain, "EQ_WINDOW_BACKGROUND", SpriteRect(0, 0, 275, 116))
    public static let EQ_TITLE_BAR_SELECTED = SpriteRef(.eqmain, "EQ_TITLE_BAR_SELECTED", SpriteRect(0, 134, 275, 14))
    public static let EQ_TITLE_BAR = SpriteRef(.eqmain, "EQ_TITLE_BAR", SpriteRect(0, 149, 275, 14))
    public static let EQ_CLOSE_BUTTON = SpriteRef(.eqmain, "EQ_CLOSE_BUTTON", SpriteRect(0, 116, 9, 9))
    public static let EQ_CLOSE_BUTTON_ACTIVE = SpriteRef(.eqmain, "EQ_CLOSE_BUTTON_ACTIVE", SpriteRect(0, 125, 9, 9))
    public static let EQ_ON_BUTTON = SpriteRef(.eqmain, "EQ_ON_BUTTON", SpriteRect(10, 119, 26, 12))
    public static let EQ_ON_BUTTON_DEPRESSED = SpriteRef(.eqmain, "EQ_ON_BUTTON_DEPRESSED", SpriteRect(128, 119, 26, 12))
    public static let EQ_ON_BUTTON_SELECTED = SpriteRef(.eqmain, "EQ_ON_BUTTON_SELECTED", SpriteRect(69, 119, 26, 12))
    public static let EQ_ON_BUTTON_SELECTED_DEPRESSED = SpriteRef(.eqmain, "EQ_ON_BUTTON_SELECTED_DEPRESSED", SpriteRect(187, 119, 26, 12))
    public static let EQ_AUTO_BUTTON = SpriteRef(.eqmain, "EQ_AUTO_BUTTON", SpriteRect(36, 119, 32, 12))
    public static let EQ_AUTO_BUTTON_DEPRESSED = SpriteRef(.eqmain, "EQ_AUTO_BUTTON_DEPRESSED", SpriteRect(154, 119, 32, 12))
    public static let EQ_AUTO_BUTTON_SELECTED = SpriteRef(.eqmain, "EQ_AUTO_BUTTON_SELECTED", SpriteRect(95, 119, 32, 12))
    public static let EQ_AUTO_BUTTON_SELECTED_DEPRESSED = SpriteRef(.eqmain, "EQ_AUTO_BUTTON_SELECTED_DEPRESSED", SpriteRect(213, 119, 32, 12))
    public static let EQ_SLIDER_THUMB = SpriteRef(.eqmain, "EQ_SLIDER_THUMB", SpriteRect(0, 164, 11, 11))
    public static let EQ_SLIDER_THUMB_SELECTED = SpriteRef(.eqmain, "EQ_SLIDER_THUMB_SELECTED", SpriteRect(0, 176, 11, 11))
    public static let EQ_PRESETS_BUTTON = SpriteRef(.eqmain, "EQ_PRESETS_BUTTON", SpriteRect(224, 164, 44, 12))
    public static let EQ_PRESETS_BUTTON_SELECTED = SpriteRef(.eqmain, "EQ_PRESETS_BUTTON_SELECTED", SpriteRect(224, 176, 44, 12))
    public static let EQ_GRAPH_BACKGROUND = SpriteRef(.eqmain, "EQ_GRAPH_BACKGROUND", SpriteRect(0, 294, 113, 19))
    public static let EQ_GRAPH_LINE_COLORS = SpriteRef(.eqmain, "EQ_GRAPH_LINE_COLORS", SpriteRect(115, 294, 1, 19))
    public static let EQ_PREAMP_LINE = SpriteRef(.eqmain, "EQ_PREAMP_LINE", SpriteRect(0, 314, 113, 1))
    // pledit.bmp
    public static let PLAYLIST_TOP_LEFT_SELECTED = SpriteRef(.pledit, "PLAYLIST_TOP_LEFT_SELECTED", SpriteRect(0, 0, 25, 20))
    public static let PLAYLIST_TITLE_BAR_SELECTED = SpriteRef(.pledit, "PLAYLIST_TITLE_BAR_SELECTED", SpriteRect(26, 0, 100, 20))
    public static let PLAYLIST_TOP_TILE_SELECTED = SpriteRef(.pledit, "PLAYLIST_TOP_TILE_SELECTED", SpriteRect(127, 0, 25, 20))
    public static let PLAYLIST_TOP_RIGHT_CORNER_SELECTED = SpriteRef(.pledit, "PLAYLIST_TOP_RIGHT_CORNER_SELECTED", SpriteRect(153, 0, 25, 20))
    public static let PLAYLIST_TOP_LEFT_CORNER = SpriteRef(.pledit, "PLAYLIST_TOP_LEFT_CORNER", SpriteRect(0, 21, 25, 20))
    public static let PLAYLIST_TITLE_BAR = SpriteRef(.pledit, "PLAYLIST_TITLE_BAR", SpriteRect(26, 21, 100, 20))
    public static let PLAYLIST_TOP_TILE = SpriteRef(.pledit, "PLAYLIST_TOP_TILE", SpriteRect(127, 21, 25, 20))
    public static let PLAYLIST_TOP_RIGHT_CORNER = SpriteRef(.pledit, "PLAYLIST_TOP_RIGHT_CORNER", SpriteRect(153, 21, 25, 20))
    public static let PLAYLIST_LEFT_TILE = SpriteRef(.pledit, "PLAYLIST_LEFT_TILE", SpriteRect(0, 42, 12, 29))
    public static let PLAYLIST_RIGHT_TILE = SpriteRef(.pledit, "PLAYLIST_RIGHT_TILE", SpriteRect(31, 42, 20, 29))
    public static let PLAYLIST_BOTTOM_TILE = SpriteRef(.pledit, "PLAYLIST_BOTTOM_TILE", SpriteRect(179, 0, 25, 38))
    public static let PLAYLIST_BOTTOM_LEFT_CORNER = SpriteRef(.pledit, "PLAYLIST_BOTTOM_LEFT_CORNER", SpriteRect(0, 72, 125, 38))
    public static let PLAYLIST_BOTTOM_RIGHT_CORNER = SpriteRef(.pledit, "PLAYLIST_BOTTOM_RIGHT_CORNER", SpriteRect(126, 72, 150, 38))
    public static let PLAYLIST_VISUALIZER_BACKGROUND = SpriteRef(.pledit, "PLAYLIST_VISUALIZER_BACKGROUND", SpriteRect(205, 0, 75, 38))
    public static let PLAYLIST_SCROLL_HANDLE = SpriteRef(.pledit, "PLAYLIST_SCROLL_HANDLE", SpriteRect(52, 53, 8, 18))
    public static let PLAYLIST_SCROLL_HANDLE_SELECTED = SpriteRef(.pledit, "PLAYLIST_SCROLL_HANDLE_SELECTED", SpriteRect(61, 53, 8, 18))
    public static let PLAYLIST_CLOSE_SELECTED = SpriteRef(.pledit, "PLAYLIST_CLOSE_SELECTED", SpriteRect(52, 42, 9, 9))
    public static let PLAYLIST_COLLAPSE_SELECTED = SpriteRef(.pledit, "PLAYLIST_COLLAPSE_SELECTED", SpriteRect(62, 42, 9, 9))
}

/// Window layouts: where each sprite is placed inside its window, in skin pixels.
public enum Layout {
    public enum Main {
        public static let size = SkinPair(275, 116)
        public static let titleBar = SpriteRect(0, 0, 275, 14)
        public static let optionsButton = SpriteRect(6, 3, 9, 9)
        public static let minimizeButton = SpriteRect(244, 3, 9, 9)
        public static let shadeButton = SpriteRect(254, 3, 9, 9)
        public static let closeButton = SpriteRect(264, 3, 9, 9)
        public static let clutterBar = SpriteRect(10, 22, 8, 43)
        public static let clutterButtons: [(String, SpriteRect)] = [("O", SpriteRect(10, 25, 8, 8)), ("A", SpriteRect(10, 33, 8, 7)), ("I", SpriteRect(10, 40, 8, 7)), ("D", SpriteRect(10, 47, 8, 8)), ("V", SpriteRect(10, 55, 8, 7))]
        public static let workIndicator = SpriteRect(24, 28, 3, 9)
        public static let playPauseIndicator = SpriteRect(26, 28, 9, 9)
        public static let minusSignLegacy = SpriteRect(40, 32, 5, 1)
        public static let minusSignEx = SpriteRect(38, 26, 9, 13)
        public static let digits: [SpriteRect] = [SpriteRect(48, 26, 9, 13), SpriteRect(60, 26, 9, 13), SpriteRect(78, 26, 9, 13), SpriteRect(90, 26, 9, 13)]
        public static let timeClickZone = SpriteRect(36, 26, 63, 13)
        public static let visualizer = SpriteRect(24, 43, 76, 16)
        public static let marquee = SpriteRect(111, 27, 154, 6)
        public static let kbps = SpriteRect(111, 43, 15, 6)
        public static let khz = SpriteRect(156, 43, 10, 6)
        public static let mono = SpriteRect(212, 41, 27, 12)
        public static let stereo = SpriteRect(239, 41, 29, 12)
        public static let volume = SpriteRect(107, 57, 68, 13)
        public static let volumeThumbY = 58
        public static let volumeThumbTravel = SkinPair(107, 158)
        public static let balance = SpriteRect(177, 57, 38, 13)
        public static let balanceThumbY = 58
        public static let balanceThumbTravel = SkinPair(177, 201)
        public static let eqButton = SpriteRect(219, 58, 23, 12)
        public static let plButton = SpriteRect(242, 58, 23, 12)
        public static let posbar = SpriteRect(16, 72, 248, 10)
        public static let posbarThumbTravel = SkinPair(16, 235)
        public static let previous = SpriteRect(16, 88, 23, 18)
        public static let play = SpriteRect(39, 88, 23, 18)
        public static let pause = SpriteRect(62, 88, 23, 18)
        public static let stop = SpriteRect(85, 88, 23, 18)
        public static let next = SpriteRect(108, 88, 22, 18)
        public static let eject = SpriteRect(136, 89, 22, 16)
        public static let shuffle = SpriteRect(164, 89, 47, 15)
        public static let `repeat` = SpriteRect(210, 89, 28, 15)
        public static let aboutLogo = SpriteRect(253, 91, 13, 15)
    }

    public enum Shade {
        public static let size = SkinPair(275, 14)
        public static let optionsButton = SpriteRect(6, 3, 9, 9)
        public static let minimizeButton = SpriteRect(244, 3, 9, 9)
        public static let shadeButton = SpriteRect(254, 3, 9, 9)
        public static let closeButton = SpriteRect(264, 3, 9, 9)
        public static let miniVisualizer = SpriteRect(79, 5, 38, 5)
        public static let timeGlyphs: [SkinPair] = [SkinPair(130, 4), SkinPair(135, 4), SkinPair(142, 4), SkinPair(147, 4)]
        public static let previous = SpriteRect(169, 4, 8, 7)
        public static let play = SpriteRect(177, 4, 10, 7)
        public static let pause = SpriteRect(187, 4, 10, 7)
        public static let stop = SpriteRect(197, 4, 9, 7)
        public static let next = SpriteRect(206, 4, 10, 7)
        public static let eject = SpriteRect(216, 4, 9, 7)
        public static let position = SpriteRect(226, 4, 17, 7)
        public static let positionThumbTravel = SkinPair(226, 240)
    }

    public enum EQ {
        public static let size = SkinPair(275, 116)
        public static let titleBar = SpriteRect(0, 0, 275, 14)
        public static let closeButton = SpriteRect(264, 3, 9, 9)
        public static let onButton = SpriteRect(14, 18, 26, 12)
        public static let autoButton = SpriteRect(40, 18, 32, 12)
        public static let presetsButton = SpriteRect(217, 18, 44, 12)
        public static let graph = SpriteRect(86, 17, 113, 19)
        public static let preampSlider = SpriteRect(21, 38, 14, 63)
        public enum BandSliders {
            public static let x0 = 78
            public static let strideX = 18
            public static let y = 38
            public static let w = 14
            public static let h = 63
            public static let count = 10
        }
        public static let sliderThumbOffsetX = 1
        public static let sliderThumbTravelY = SkinPair(0, 51)
    }

    public enum Playlist {
        public static let minSize = SkinPair(275, 116)
        public static let defaultSize = SkinPair(275, 232)
        public static let resizeStep = SkinPair(25, 29)
        public static let titleHeight = 20
        public static let bottomHeight = 38
        public static let leftWidth = 12
        public static let rightWidth = 20
        public static let closeButtonFromTopRight = SpriteRect(-11, 3, 9, 9)
        public static let rowHeight = 13
        public static let scrollHandleFromRight = -15
        public static let runningInfoFromBottomRight = SkinPair(-143, -28)
        public static let miniTimeFromBottomRight = SkinPair(-87, -15)
    }
}

/// The classic 5x6 bitmap font living in text.bmp.
public enum SkinFontSpec {
    public static let glyphWidth = 5
    public static let glyphHeight = 6
    public static let columns = 31
    public static let rows: [String] = [
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ\"@",
        "0123456789….:()-'!_+\\/[]^&%,=$#",
        "ÅÖÄ?*",
    ]
    public static let spaceCell = (row: 0, col: 30)
}
